### ISSUE TITLE
PHP 7.4 deprecated warning (curly braces)

### ISSUE THREAD

**Issue by gingebaker** [BlowbackDesign/EmailObfuscation#12]
Hi
Just added your module on a PHP 7.4 installation.
There are some deprecated Infos:

> Deprecated: Array and string offset access syntax with curly braces is deprecated in /site/modules/EmailObfuscation/EmailObfuscation.module on line 239

Replacing the curly braces with squares  in the base64 function should fix this:

```php
/**
 * custom base 64 encoding
 *
 */
private function base64($data)
{
	$out = '';
	$key = $this->getKey();
	for($i = 0; $i < strlen($data); ) {
		$c1 = ord($data[$i++]);
		$c2 = $c3 = NULL;
		if($i < strlen($data)) $c2 = ord($data[$i++]);
		if($i < strlen($data)) $c3 = ord($data[$i++]);
		$e1 = $c1 >> 2;
		$e2 = (($c1 & 3) << 4) + ($c2 >> 4);
		$e3 = (($c2 & 15) << 2) + ($c3 >> 6);
		$e4 = $c3 & 63;
		if(is_nan($c2)) $e3 = $e4 = 64;
		else if(is_nan($c3)) $e4 = 64;
		$out .= $key[$e1] . $key[$e2] . $key[$e3] . $key[$e4];
	}
	return $out;
}
```
Anyway, thanks for this great module!

**Comment by processwired** [comment]
I'm getting the same issues with PHP 7.4 and would be glad if this could be fixed. Another hint: I'm not sure if $data could ever contain multibyte data, but generally it's a good idea to use mb_strlen($data) instead of strlen($data).

**Many thanks for this module! I use it in almost every ProcessWire instance of mine.**
